site_name: Montres russes
theme:
    name: minty
    nav_style: dark
    hljs_languages:
        - yaml
        - rust
        - bash
nav:
    - Home: 'index.md'
    - 'Les montres par marques':
        - 'Pobeda': 'pobeda.md'
        - 'Poljot': 'poljot.md'
        - 'Raketa': 'raketa.md'
        - 'Slava': 'slava.md'
    - Les Fabriques: 'fabriques.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
